from .BasicModule import BasicModule
from .model_1 import model_1
from .model_2 import model_2
from .model_3 import model_3
from .model_4 import model_4
from .model_cnn_1 import CNN
from .model_cnn_1 import CNN2
from .model_cnn_1 import CNN_noip_noport_noprot
from .model_cnn_1 import CNN_onlymac
#from .model_cnn_lstm import CNN_LSTM
from .model_5 import LSTM
from .model_5 import LinearLSTM
from .model_5 import CNN_LSTM
from .model_5 import CNN_LSTM2
from .model_5 import LSTM_CNN
